### ISSUE TITLE
Package depends on any version of pyprob, this is a problem

### ISSUE THREAD

**Issue by mitar** [tonyjo/ubc_primitives#1]
Originally, pyprob was installed with `1.2.0`, but now it is installing with `1.2.1` has requirement `torch>=1.5.1`, but we have torch `1.4.0` in the D3M Docker image.

Please fix the upper versions of your primitives.

**Comment by tonyjo** [comment]
PyProb fixed in requirements to 1.2.0.

**Comment by mitar** [comment]
You will have to resubmit primitive annotations.

**Comment by tonyjo** [comment]
Resubmitted primitive annotations
